### PR TITLE
Data buffer fixes

### LINKED ISSUE #23: Handle SQLGetData buffer overflows
Sometimes the reported column size (number of characters in text representation of the column values) may be too small for some values of the column. If, due to this, we use a too small buffer in `SQLGetData` the result will be `SQL_SUCCESS_WITH_INFO` and the whole representation of the data must be obtained by calling `SQLGetData` multiple times. The details are [here](https://msdn.microsoft.com/en-us/library/ms715441(v=vs.85).aspx)

For numeric types the precision is truncated in case of a small buffer and the whole representation cannot be retrieved (this can happen frequently of drivers that access data in flat formats such as CSV or TSV, e.g. Hive, since the number representation size is estimated from a sample of rows). To avoid this loss of precision we can use appropriate minimum buffer sizes for numeric types.

For some drivers, I've noticed that text data returned by `SQLGetData` may not be zero-terminated in case of overflow, contradicting the documentation. We should handle this situation as well.

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #23

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rafatower please review. I think review may be easier looking at each commit in isolation

File: odbc_fdw.c [hunk 1]
```diff
@@ -517,7 +527,13 @@ sql_data_type(
...
 			break;
 		case SQL_BIT :
-		    appendStringInfo(sql_type, "bit(1)");
+			/* Use boolean instead of bit(1) because:
+			 * * binary types are not yet fully supported
+			 * * boolean is more commonly used in PG
+			 * * With options BoolsAsChar=0 this allows
+			 *   preserving boolean columns from pSQL ODBC.
+			 */
+		    appendStringInfo(sql_type, "boolean");
```
Comment (rafatower) [inline odbc_fdw.c]: indentantion

please start using a linter or fomater of your choice.

File: odbc_fdw.c [hunk 2]
```diff
@@ -526,12 +542,14 @@ sql_data_type(
 		case SQL_BIGINT :
 			appendStringInfo(sql_type, "bigint");
 			break;
+		/*
```
Comment (rafatower) [inline odbc_fdw.c]: are you sure you want to comment this block out?

File: odbc_fdw.c [hunk 3]
```diff
@@ -1289,15 +1339,35 @@ odbcIterateForeignScan(ForeignScanState *node)
...
+				conversion = BIN_CONVERSION;
+			}
 
 			/* Get the position of the column in the FDW table */
 			for (k=0; k<num_of_table_cols; k++)
 			{
 				if (strcmp(table_columns[k].data, (char *) ColumnName) == 0)
 				{
+					SQLULEN min_size = minimum_buffer_size(DataTypePtr);
+					SQLULEN max_size = 8192;
```
Comment (rafatower) [inline odbc_fdw.c]: what types are affected by this hardoced limitation?

File: odbc_fdw.c [hunk 4]
```diff
@@ -1358,8 +1433,87 @@ odbcIterateForeignScan(ForeignScanState *node)
...
+			buf_used = 0;
 			ret = SQLGetData(stmt, i, SQL_C_CHAR,
 							 buf, sizeof(char) * (col_size+1), &indicator);
+			buf_used = indicator;
+
+			if (ret == SQL_SUCCESS_WITH_INFO)
+			{
+				SQLCHAR sqlstate[5];
+				SQLGetDiagRec(SQL_HANDLE_STMT, stmt, 1, sqlstate, NULL, NULL, 0, NULL);
+				if (strcmp((char*)sqlstate, "01S07") == 0)
```
Comment (rafatower) [inline odbc_fdw.c]: what's the meaning of `"01S07"`? isn't it better as a "named constant"?

File: odbc_fdw.c [hunk 5]
```diff
@@ -1358,8 +1433,87 @@ odbcIterateForeignScan(ForeignScanState *node)
...
+								accum_buffer = new_buff;
+								accum_buffer[accum_used] = 0;
+							}
+							// Copy part to the accumulation buffer
+							strncpy(accum_buffer+accum_used, buf, buf_len);
+							accum_used += buf_len;
+							accum_buffer[accum_used] = 0;
+							// Get new part
+							if (ret != SQL_SUCCESS_WITH_INFO)
+							  break;
```
Comment (rafatower) [inline odbc_fdw.c]: - I'd be wary of a while(1) with such break. Is this guaranteed to exit?

- the nesting level makes this hard to understand. I'm tempted of adding a linter with cyclomatic complexity measure, could this be rewritten in a more readable way?

File: odbc_fdw.c [hunk 6]
```diff
@@ -1377,7 +1531,25 @@ odbcIterateForeignScan(ForeignScanState *node)
 						buf = pg_any_to_server(buf, strlen(buf), festate->encoding);
 					}
 				 	initStringInfo(&col_data);
-				 	appendStringInfoString (&col_data, buf);
+					if (conversion == HEX_CONVERSION)
```
Comment (rafatower) [inline odbc_fdw.c]: isn't this block more suitable for a switch-case?

**Comment by rafatower** [comment]
My understanding is that this fixes some issues found with pg driver, right?

What are the chances of breaking any of the working drivers with this patch? what can be done to mitigate that risk?

File: odbc_fdw.c (hunk 1 above)
Comment (jgoizueta) [inline odbc_fdw.c]: I think that misalignment is due to how github handles tabs, but I sure do need a linter

File: odbc_fdw.c (hunk 2 above)
Comment (jgoizueta) [inline odbc_fdw.c]: Yes, the translation is correct (SQL_BINARY to bit(...) and SQL_VARBINARY to varbit(...)) but we reading thos values is complicated, so we don't support it yet. So we leave the sql_type blank which now makes the column to be ignored.

File: odbc_fdw.c (hunk 3 above)
Comment (jgoizueta) [inline odbc_fdw.c]: Text (longvarchar in odbc parlance). In a text column coming from a PostGIS geometry we were getting a size larger than 1M.

This doesn't limit the data that we can read, since we can read it in chunks. But avoids using 1M chunks for every piece of data.

File: odbc_fdw.c (hunk 4 above)
Comment (jgoizueta) [inline odbc_fdw.c]: It's the ODBC SQLSTATE for "Fractional truncation".

I'll define a constant to make it more clear.

File: odbc_fdw.c (hunk 5 above)
Comment (jgoizueta) [inline odbc_fdw.c]: I'll give it a try at rewriting this.

Than middle-of-the-loop exit point must eventually be take because `GetData` only returns `SQL_SUCCESS_WITH_INFO` until the whole data has been read.

File: odbc_fdw.c (hunk 6 above)
Comment (jgoizueta) [inline odbc_fdw.c]: Mmmm, yes it is.

**Comment by jgoizueta** [comment]
This deals with problems found with Hive and PG (but could affect other drivers too), namely:

* The driver reported size for a column may be insufficient for all its values
* A number for which the read buffer is too small will be truncated and we cannot read it in parts
* The reported size of column can be huge for varying-size columns
* PG booleans are mapped to ODBC bit(1) or char(5) depending on a parameter
* ODBC LongVarBinary type is formatted as hexadecimal when read through a C string (so this, unlike the bit strings can be read easily into a bytea).

It has been tested with PG, MySQL and Hive.

File: odbc_fdw.c (hunk 2 above)
Comment (rafatower) [inline odbc_fdw.c]: then I'd remove the block and rely on git to remember the history

File: odbc_fdw.c (hunk 5 above)
Comment (jgoizueta) [inline odbc_fdw.c]: I'll leave this for later at #25 to speed up current release

Comment (rafatower) [inline odbc_fdw.c]: ok, sure
